[build]
builder = "nixpacks"

[deploy]
# Use this startCommand if root directory cannot be set in dashboard
startCommand = "cd real-estate-map/backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

